apiVersion: v1
kind: Service
metadata:
  name: goordersb
  labels:
    app: goordersb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: goordersb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goordersb
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: goordersb
        app: goordersb
    spec:
      containers:
      - name: goordersb
        image: <yourcontainerregistry>.azurecr.io/go_order_sb
        env:
        - name: DATABASE
          value: ""
        - name: PASSWORD
          value: ""
        - name: INSIGHTSKEY
          value: ""
        - name: SOURCE
          value: "K8"
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: <yourcontainerregistry>